# Usar a imagem base do Ubuntu
FROM ubuntu:20.04

# Atualizar e instalar dependências necessárias
RUN apt-get update && apt-get install -y \
    python3 \
    python3-pip \
    wget

# Instalar bibliotecas Python
RUN pip3 install beautifulsoup4 requests

# Copiar os scripts para o contêiner
COPY scrape.sh /app/
COPY data_cleaning.py /app/

# Definir o diretório de trabalho
WORKDIR /app

# Definir o comando padrão para o contêiner
CMD ["bash", "scrape.sh"]
