# Usar a imagem base do Node.js
FROM node:18

# Criar diretório de trabalho
WORKDIR /app

# Copiar package.json e package-lock.json
COPY package*.json ./

# Instalar dependências
RUN npm install

# Copiar todos os arquivos do diretório atual
COPY . .

# Expor a porta que o servidor vai usar
EXPOSE 3000

# Comando para rodar o servidor
CMD ["node", "server.js"]
